MIN_LOGIN_LENGTH = 3
MAX_LOGIN_LENGTH = 50
MIN_PASSWORD_LENGTH = 5
SQLALCHEMY_DATABASE_URI = 'sqlite:///users.db'
MONGODB_CONNECTION_URI = 'mongodb://localhost:27017'
BASE_PATH = '/api/v1.0'
TOKEN_LIFETIME = 3600